spring.data.rest.base-path=/api
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/k26Salipaivakirja
spring.datasource.username=postgres
spring.datasource.password=15032000JkJp

spring.jpa.hibernate.ddl-auto=none